version: '3.7'
services:
  link-simplier-app:
    ports:
      - "8888:8080"
    environment:
      - TZ=Europe/Moscow
    build:
      context: .
      dockerfile: Dockerfile
    restart: always

networks:
  default:
    name: link-simplier-network
