server.port: 8888

logging:
  file.path: ./logs
  level:
    org.springframework.web: OFF
    root: INFO

spring:
  liquibase:
    enabled: true
  jpa:
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
  datasource:
    url: jdbc:postgresql://localhost:5555/postgres
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  redis:
    port: 6379
